---
# build and install httpd_2.2

- name :  Install package needed to build httpd source file 
  yum : 
    name :  "{{ item }}"
    state : present
  with_items :
    - pcre-devel  
     
- name :  Download the source file of httpd 
  get_url : 
    url :  "{{ apache_2_2.url }}"
    dest : "{{ apache_2_2.work_dir }}"  
       

- name: httpd のパッケージ化(rpm)
  shell: rpmbuild -ta --clean "{{ apache_2_2.src_filename }}"
  args:
    chdir: "{{ apache_2_2.work_dir }}"
    creates: "{{ apache_2_2.rpm_directory }}/{{ apache_2_2.rpm_filenames.0 }}"

- name :  directory for placing the httpd package 
  file : 
    path :  " {{ apache_2_2.rpm_directory }}"
    state : directory
    owner : root
    group : root
    mode : 0755  
     
- name: httpd のパッケージ配置
  shell: find "{{ apache_2_2.rpmbuild_dir }}" -name '*.rpm' | xargs -i mv {} .
  args:
    chdir: "{{ apache_2_2.rpm_directory }}"
    creates: "{{ apache_2_2.rpm_directory }}/{{ apache_2_2.rpm_filenames.0 }}"

- name: httpd のインストール
  yum:
    name: "{{ apache_2_2.rpm_directory }}/{{ item }}"
    state: present
  with_items: "{{ apache_2_2.rpm_filenames }}"

- name: 起動ユーザ・グループ設定
  lineinfile:
    dest: "{{ apache_2_2.conf_file}}"
    backrefs: yes
    regexp: '{{ item.regexp}}'
    line: '{{ item.line }}'
  with_items:
    - regexp: "^User.*"
      line: "User {{ apache_2_2.user_name}}"
    - regexp: "^Group.*"
      line: "Group {{ apache_2_2.group_name}}"
  notify: restart httpd

- name: DocumetRoot の変更
  replace:
    dest: "{{ apache_2_2.conf_file}}"
    regexp: "/var/www/htdocs"
    replace: "/var/www/html"
  notify: restart httpd

- name :  Service activation of httpd · Autostart setting 
  service : 
    name :  httpd 
    enabled :  yes