---
# build and install distcache-devel

- name:  Download distcache source file
  get_url : 
    url :  "{{ distcache.url }}"
    dest : "{{ apache_2_2.work_dir}}"  
      

- name: distcache のパッケージ化(rpm)
  shell: "rpmbuild --rebuild {{ distcache.src_filename }}"
  args:
    chdir: "{{ apache_2_2.work_dir}}"
    creates: "{{ distcache.rpm_directory }}/{{ distcache.rpm_filenames.1 }}"

- name :  directory for distributing package 
  file : 
    path :  " {{ distcache.rpm_directory }}"
    state : directory
    owner : root
    group : root
    mode : 0755 

- name: distcache のパッケージ配置
  shell: "find {{ apache_2_2.rpmbuild_dir }} -name '*.rpm' | xargs -i mv {} ."
  args:
    chdir: "{{ distcache.rpm_directory }}"
    creates: "{{ distcache.rpm_directory }}/{{ distcache.rpm_filenames.1 }}"

- name: distcache-devel のインストール
  yum:
    name: "{{ distcache.rpm_directory }}/{{ item }}"
    state: present
  with_items: "{{ distcache.rpm_filenames }}"